### ISSUE TITLE
Exception misreported for ldaps certificate error

### ISSUE THREAD

**Issue by tomgriffinstfc** [icatproject/authn.ldap#2]
If the plug is configured to use ldaps://, but the certificate is not installed, an SSL Handshake exception occurs. 

ICAT/auth_ldap reports this to the user as "The username and password do not match"
Nothing is logged to auth_ldap.log

The returned exception should be more specific (and logging even more so) to make the configuration/certificate error easier to spot.

**Comment by tomgriffinstfc** [comment]
#4 was caused due to this behaviour

**Comment by ajkyffin** [comment]
This now reports `javax.naming.CommunicationException: simple bind failed`
