### ISSUE TITLE
Can't get ldaps (secure) URLs to work with authn.ldap-1.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by kevinphippsstfc** [icatproject/authn.ldap#4]
I’ve installed authn.ldap-1.2.0-SNAPSHOT but I can’t get it to work with an “ldaps” url. Tom recommended that we change to ldaps URLs a couple of weeks ago and indeed I have done it on a couple of servers and it works.

However, with authn.ldap-1.2.0-SNAPSHOT the following property does not work:

provider_url = ldaps://logon05.fed.cclrc.ac.uk

but without the “s” it does. ie.

provider_url = ldap://logon05.fed.cclrc.ac.uk

Do you know what you might have changed to cause this?

I did not have an older LDAP authenticator installed on this particular machine so cannot say if it worked previously on this machine, but I’ve certainly got the old version working with ldaps on a couple of other servers.

**Comment by tomgriffinstfc** [comment]
ldaps:// requires the ldap server certificte to be installed in glassfish
